import { Camera, Cpu, ShieldCheck } from 'lucide-react';

export const COPY = {
  en: {
    nav: { technology: 'Technology', project: 'Project', demo: 'Live Demo', workflow: 'Workflow', start: 'Start Demo', stop: 'Stop Camera' },
    hero: {
      eyebrow: 'Computer vision for silent speech',
      title: 'Lip-reading intelligence for accessible interaction.',
      body: 'LipReading.AI turns camera-based lip landmarks into structured predictions, helping teams prototype assistive interfaces, silent command systems, and vision-driven communication tools.',
      primary: 'Try the model',
      secondary: 'View technology',
      note: 'Model note: prediction is trained for Indonesian words only.',
    },
    metrics: [
      { label: 'Frame sequence', value: '90' },
      { label: 'Lip features', value: '64' },
      { label: 'Payload type', value: 'Landmarks' },
    ],
    capabilitiesTitle: 'A practical vision layer for speech-adjacent products.',
    capabilitiesEyebrow: 'What we build',
    capabilities: [
      { icon: Camera, title: 'Vision Capture', copy: 'Face landmarks are detected in browser and converted into clean lip vectors.' },
      { icon: Cpu, title: 'Model Ready', copy: 'Every session is shaped into a fixed 90-frame sequence for the trained classifier.' },
      { icon: ShieldCheck, title: 'Private First', copy: 'The browser sends landmark numbers to the API, not a raw recorded video file.' },
    ],
    console: {
      eyebrow: 'Recognition console',
      title: 'Live landmark pipeline',
      vector: 'Vector build',
      features: 'features per frame',
      payload: 'landmark payload',
      latest: 'Latest result',
      awaiting: 'Awaiting speech',
      prompt: 'Start the demo and speak toward the camera.',
      confidence: 'confidence',
    },
    demo: {
      eyebrow: 'Interactive product demo',
      title: 'Camera landmark recognition',
      cameraOff: 'Camera is off',
      capture: 'Capture progress',
      prediction: 'Prediction',
      analyzing: 'Analyzing landmarks',
      empty: 'No prediction yet. Start the camera and speak once the status is ready.',
      history: 'Recent history',
      noHistory: 'No history yet',
    },
    workflow: {
      eyebrow: 'Workflow',
      title: 'From camera signal to model input.',
      body: 'The frontend handles landmark extraction and sequence shaping so the backend receives the exact vector contract expected by the trained model.',
      badge: 'Browser landmark pipeline',
      steps: [
        'Detect facial landmarks from the live camera stream.',
        'Extract selected lip points and normalize each frame.',
        'Build a 90-frame landmark sequence and send it to the prediction API.',
      ],
    },
    backend: {
      eyebrow: 'Backend intelligence',
      title: 'What the API and model actually run.',
      body: 'The backend is a FastAPI service that loads the augmented TensorFlow GRU model and accepts a flat landmark vector from the frontend.',
      cards: [
        { label: 'Runtime', value: 'FastAPI + TensorFlow', detail: 'Served with Uvicorn on port 8000, Docker-ready with CPU TensorFlow settings.' },
        { label: 'Production model', value: 'lip_reading_aug.h5', detail: 'Augmented GRU model loaded on API startup and used by POST /predict.' },
        { label: 'Input contract', value: '5760 floats', detail: '90 frames x 64 lip features, reshaped to (1, 90, 64) before inference.' },
        { label: 'Classes', value: '21 Indonesian words', detail: 'The label map contains Indonesian vocabulary such as buka, tutup, menulis, pembelajaran, and komunikasi.' },
      ],
      pipelineTitle: 'Extraction pipeline',
      pipeline: [
        'OpenCV reads training videos as BGR frames, then converts them to RGB for MediaPipe.',
        'MediaPipe FaceLandmarker detects the face and extracts 32 selected lip points.',
        'Each frame is centered by mean position and scaled by maximum absolute distance.',
        'Sequences shorter than 90 frames duplicate the last frame; longer sequences are cut to 90 frames.',
      ],
      trainingTitle: 'Training and evaluation',
      training: [
        'Augmentation produces original, slow motion, rotation -10, rotation +10, and zoom variants.',
        'The model uses stacked GRU layers 128 then 64, BatchNorm, Dropout, Dense, and softmax output.',
        'The V3 training split is grouped per original video to avoid train-validation leakage.',
        'Augmented report accuracy is 0.91 with macro F1 0.92 on the grouped original holdout set.',
      ],
      stats: [
        { value: '581', label: 'base samples' },
        { value: '2905', label: 'augmented samples' },
        { value: '64', label: 'epochs trained' },
        { value: '0.91', label: 'report accuracy' },
      ],
    },
    prefs: {
      title: 'Preferences',
      body: 'Stores language and theme only.',
      light: 'Light',
      dark: 'Dark',
      accept: 'Save',
    },
    status: {
      cameraOff: 'CAMERA OFF',
      cameraOn: 'CAMERA ON',
      recording: 'RECORDING 90 FRAMES',
      analyzing: 'ANALYZING',
      recognized: 'RECOGNIZED',
      cooldown: 'COOLDOWN',
      validating: 'VALIDATING',
      ready: 'READY',
    },
    footer: 'Computer vision company profile and live lip-reading prototype.',
  },
  id: {
    nav: { technology: 'Teknologi', project: 'Project', demo: 'Demo Langsung', workflow: 'Alur Kerja', start: 'Mulai Demo', stop: 'Matikan Kamera' },
    hero: {
      eyebrow: 'Computer vision untuk silent speech',
      title: 'Teknologi lip-reading untuk interaksi yang lebih aksesibel.',
      body: 'LipReading.AI mengubah landmark bibir dari kamera menjadi prediksi terstruktur untuk prototipe antarmuka bantu, silent command, dan alat komunikasi berbasis vision.',
      primary: 'Coba model',
      secondary: 'Lihat teknologi',
      note: 'Catatan model: prediksi saat ini hanya dilatih untuk kata bahasa Indonesia.',
    },
    metrics: [
      { label: 'Panjang sequence', value: '90' },
      { label: 'Fitur bibir', value: '64' },
      { label: 'Tipe payload', value: 'Landmarks' },
    ],
    capabilitiesTitle: 'Lapisan vision yang praktis untuk produk berbasis speech-adjacent.',
    capabilitiesEyebrow: 'Yang kami bangun',
    capabilities: [
      { icon: Camera, title: 'Vision Capture', copy: 'Landmark wajah dideteksi di browser lalu diubah menjadi vector bibir yang rapi.' },
      { icon: Cpu, title: 'Model Ready', copy: 'Setiap sesi dibentuk menjadi sequence tetap 90 frame untuk classifier yang sudah dilatih.' },
      { icon: ShieldCheck, title: 'Private First', copy: 'Browser mengirim angka landmark ke API, bukan file video mentah.' },
    ],
    console: {
      eyebrow: 'Recognition console',
      title: 'Pipeline landmark langsung',
      vector: 'Vector build',
      features: 'fitur per frame',
      payload: 'payload landmark',
      latest: 'Hasil terbaru',
      awaiting: 'Menunggu ucapan',
      prompt: 'Mulai demo dan ucapkan kata ke arah kamera.',
      confidence: 'confidence',
    },
    demo: {
      eyebrow: 'Demo produk interaktif',
      title: 'Pengenalan landmark kamera',
      cameraOff: 'Kamera mati',
      capture: 'Progress capture',
      prediction: 'Prediksi',
      analyzing: 'Menganalisis landmark',
      empty: 'Belum ada prediksi. Nyalakan kamera dan bicara saat status ready.',
      history: 'Riwayat terbaru',
      noHistory: 'Belum ada riwayat',
    },
    workflow: {
      eyebrow: 'Alur kerja',
      title: 'Dari sinyal kamera ke input model.',
      body: 'Frontend menangani ekstraksi landmark dan pembentukan sequence agar backend menerima kontrak vector yang sesuai dengan model.',
      badge: 'Browser landmark pipeline',
      steps: [
        'Deteksi landmark wajah dari stream kamera langsung.',
        'Ambil titik bibir terpilih dan normalisasi setiap frame.',
        'Bentuk sequence landmark 90 frame lalu kirim ke API prediksi.',
      ],
    },
    backend: {
      eyebrow: 'Intelligence backend',
      title: 'Yang benar-benar berjalan di API dan model.',
      body: 'Backend memakai FastAPI untuk load model TensorFlow GRU augmented dan menerima vector landmark flat dari frontend.',
      cards: [
        { label: 'Runtime', value: 'FastAPI + TensorFlow', detail: 'Disajikan dengan Uvicorn di port 8000, siap Docker, dan diset untuk TensorFlow CPU.' },
        { label: 'Model production', value: 'lip_reading_aug.h5', detail: 'Model GRU augmented dimuat saat API startup dan dipakai oleh POST /predict.' },
        { label: 'Kontrak input', value: '5760 floats', detail: '90 frame x 64 fitur bibir, lalu reshape ke (1, 90, 64) sebelum inference.' },
        { label: 'Kelas', value: '21 kata Indonesia', detail: 'Label map berisi vocabulary Indonesia seperti buka, tutup, menulis, pembelajaran, dan komunikasi.' },
      ],
      pipelineTitle: 'Pipeline ekstraksi',
      pipeline: [
        'OpenCV membaca video training sebagai frame BGR, lalu dikonversi ke RGB untuk MediaPipe.',
        'MediaPipe FaceLandmarker mendeteksi wajah dan mengambil 32 titik bibir terpilih.',
        'Setiap frame di-center berdasarkan rata-rata posisi dan diskalakan dengan jarak absolut maksimum.',
        'Sequence kurang dari 90 frame menduplikasi frame terakhir; lebih dari 90 frame dipotong.',
      ],
      trainingTitle: 'Training dan evaluasi',
      training: [
        'Augmentasi menghasilkan varian original, slow motion, rotation -10, rotation +10, dan zoom.',
        'Arsitektur model memakai GRU bertingkat 128 lalu 64, BatchNorm, Dropout, Dense, dan softmax.',
        'Training V3 memakai split per original video supaya tidak terjadi train-validation leakage.',
        'Report augmented mencapai accuracy 0.91 dengan macro F1 0.92 pada holdout original yang grouped.',
      ],
      stats: [
        { value: '581', label: 'base samples' },
        { value: '2905', label: 'augmented samples' },
        { value: '64', label: 'epoch trained' },
        { value: '0.91', label: 'report accuracy' },
      ],
    },
    prefs: {
      title: 'Preferensi',
      body: 'Menyimpan bahasa dan tema saja.',
      light: 'Terang',
      dark: 'Gelap',
      accept: 'Simpan',
    },
    status: {
      cameraOff: 'KAMERA MATI',
      cameraOn: 'KAMERA ON',
      recording: 'REKAM 90 FRAME',
      analyzing: 'ANALISIS',
      recognized: 'TERDETEKSI',
      cooldown: 'COOLDOWN',
      validating: 'VALIDASI',
      ready: 'READY',
    },
    footer: 'Company profile computer vision dan prototipe lip-reading langsung.',
  },
};

export function getShell(theme) {
  const isDark = theme === 'dark';
  return isDark
    ? {
      page: 'bg-[#0f1110] text-[#f4f1ea]',
      header: 'border-[#2e3431] bg-[#0f1110]/90',
      muted: 'text-[#b7afa4]',
      soft: 'border-[#2e3431] bg-[#171a18]',
      card: 'border-[#2e3431] bg-[#171a18]',
      panel: 'border-[#2e3431] bg-[#111413]',
      ink: 'text-[#f4f1ea]',
    }
    : {
      page: 'bg-[#f6f3ee] text-[#171717]',
      header: 'border-[#ded8cd] bg-[#f6f3ee]/90',
      muted: 'text-[#6d665c]',
      soft: 'border-[#d8d1c5] bg-white',
      card: 'border-[#e1dbd1] bg-[#fbfaf7]',
      panel: 'border-[#d8d1c5] bg-white',
      ink: 'text-[#171717]',
    };
}
